[package]
name = "convey"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
reqwest = "0.12.12"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.137"
tui-tree-widget = "0.23.0"
uuid = { version = "1.12.1", features = ["v4"] }
